apiVersion: v1
kind: Pod
metadata:
  name: configuration
  labels:
    project: roboshop
    environment: dev
    purpose: config
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - configMapRef:
      name: pod-config